version:  '3.0'
services:
  php-fpm:
    build:
        context: .
        dockerfile: php.Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/zhaojunlike/lnmp-php-fpm:5.6-latest
    restart: always
    environment:
        DEV_APP_DEBUG: 0
        APP_DEBUG: 0
        APP_TRACE: 0
    volumes:
      - ./app:/app:rw
      - /etc/localtime:/etc/localtime:ro
      - ./dockerfiles/php/php-pro.ini:/usr/local/etc/php/php.ini:ro
      - ./dockerfiles/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
    command: php-fpm
  nginx:
    build:
        context: .
        dockerfile: nginx.Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/zhaojunlike/lnmp-nginx:1.13.3
