version:  '3.0'
services:
  php-fpm:
    image: registry.cn-hangzhou.aliyuncs.com/zhaojunlike/lnmp-php-fpm:5.6-latest
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 3
    volumes:
      - "/var/log/php-fpm"
      - "/etc/localtime:/etc/localtime:ro"
    command: php-fpm
    links:
        - "mysql-db:mysql-db"
        - "redis-db:redis-db"
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/zhaojunlike/lnmp-nginx:1.13.3
    links:
      - "php-fpm:php-fpm"
    ports:
      - "80:80"
    deploy:
      restart_policy:
        condition: any
    command: nginx -g 'daemon off;'
  mysql-db:
    image: mysql:5.7
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:
        MYSQL_ROOT_PASSWORD: zhaojun
        MYSQL_DATABASE: lnmp_db
        MYSQL_USER: zhaojun
        MYSQL_PASSWORD: zhaojun
    deploy:
      restart_policy:
        condition: any
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
  redis-db:
    image: redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      restart_policy:
        condition: any
